services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rathan@156
      POSTGRES_DB: postgres
    networks:
      - backend
    ports:
      - "5000:5432"
    volumes:
      - ~/db-volumes/patient-service-db:/var/lib/postgresql/data

  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rathan@156
      POSTGRES_DB: postgres
    networks:
      - backend
    ports:
      - "5001:5432"
    volumes:
      - ~/db-volumes/auth-service-db:/var/lib/postgresql/data

  patient-service:
    build:
      context: ./patient-service
    image: patient-service:latest
    container_name: patient-service
    depends_on:
      - patient-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Rathan@156
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_SQL_INIT_MODE: always
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: ["sh", "-c", "sleep 10 && java -jar app.jar"]
    networks:
      - backend

  billing-service:
    build:
      context: ./billing-service
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - backend

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
    networks:
     - backend

  analytics-service:
    build:
      context: ./analytics-service
    image: analytics-service:latest
    container_name: analytics-service
    ports:
      - "4002:4002"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - backend

  auth-service:
    build:
      context: ./auth-service
    image: auth-service:latest
    container_name: auth-service
    depends_on:
      - auth-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Rathan@156
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: "Wz7oAdwVlgf8SkAxMEJf2k3TGpHvIqkX0K6REK3pq2B6LVc/8ntjS+nGVv0u+mABpYtqvCBIMxJp+jTk6XkHFw=="
    command: ["sh", "-c", "sleep 10 && java -jar app.jar"]
    networks:
      - backend

  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "4004:4004"
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
    networks:
      - backend

networks:
  backend:
    driver: bridge
